image: node:latest

stages:
    - test
    - staging
    - production

test:
    type: test
    stage: test
    script:
        - cd ./tests
        - wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz; mkdir geckodriver; tar -xzf geckodriver-v0.26.0-linux64.tar.gz -C geckodriver; export PATH=$PATH:$PWD/geckodriver;
        - yarn install
        - yarn test
    only:
        - master

staging:
    type: deploy
    stage: staging
    image: ruby:latest
    script:
        - apt-get update -qy
        - apt-get install -y ruby ruby-dev rubygems-integration
        - gem install dpl
        - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY --skip_cleanup
    only:
        - staging

production:
    type: deploy
    stage: production
    image: ruby:latest
    script:
        - apt-get update -qy
        - apt-get install -y ruby ruby-dev rubygems-integration
        - gem install dpl
        - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY --skip_cleanup
    only:
        - master